specVersion: 0.0.1
description: ''
repository: 'git@github.com:bifrost-finance/bifrost-subql.git'
schema: ./schema.graphql
network:
  endpoint: 'wss://bifrost-rpc.testnet.liebi.com'
  types: {
    "TokenSymbol": {
        "_enum": {
            "ASG": 0,
            "aUSD": 1,
            "DOT": 2,
            "vDOT": 3,
            "KSM": 4,
            "vKSM": 5,
            "ETH": 6,
            "vETH": 7,
            "EOS": 8,
            "vEOS": 9,
            "IOST": 10,
            "vIOST": 11
        }
    },
    "CurrencyId": {
        "_enum": {
            "Token": "TokenSymbol"
        }
    },
    "AmountOf": "i128",
    "ChainId": {
        "_enum": {
            "RelayChain": "Null",
            "ParaChain": "ParaId"
        }
    },
    "XCurrencyId": {
        "chainId": "ChainId",
        "currencyId": "Vec<u8>"
    },
    "CurrencyIdOf": "CurrencyId",
    "IsExtended": "bool",
    "StorageVersion": "Releases",
    "ShareWeight": "Balance",
    "PalletBalanceOf": "Balance",
    "BlockNumberFor": "BlockNumber",
    "NumberOrHex": {
        "_enum": {
            "Number": "u64",
            "Hex": "U256"
        }
    },
    "TokenBalance": "Balance",
    "TokenId": "u32",
    "PairId": "u32",
    "Pair": {
        "token_0": "AssetId",
        "token_1": "AssetId",
        "account": "AccountId",
        "total_liquidity": "TokenBalance",
        "lp_asset_id": "AssetId"
    },
    "PairInfo": {
        "token_0": "AssetId",
        "token_1": "AssetId",
        "account": "AccountId",
        "total_liquidity": "TokenBalance",
        "holding_liquidity": "TokenBalance",
        "reserve_0": "TokenBalance",
        "reserve_1": "TokenBalance",
        "lp_asset_id": "AssetId"
    },
    "AssetId": {
        "chain_id": "u32",
        "module_index": "u8",
        "asset_index": "u32"
    },
    "AssetProperty": {
        "_enum": {
            "Foreign": null,
            "Lp": "LpProperty"
        }
    },
    "LpProperty": {
        "token_0": "AssetId",
        "token_1": "AssetId"
    },
    "PalletId": "u32"
}
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        # - handler: handleBlock
        #   kind: substrate/BlockHandler
        # - handler: handleEvent
        #   kind: substrate/EventHandler
        #   filter:
        #     module: balances
        #     method: Deposit
        # - handler: handleCall
        #   kind: substrate/CallHandler
        # mappingVtokenPool.ts:
        - handler: vtokenPoolBlock
          kind: substrate/BlockHandler
        - handler: assetsTransferredEvent
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred
        - handler: assetsIssuedEvent
          kind: substrate/EventHandler
          filter:
            module: brmlAssets
            method: Issued
        - handler: assetsBurnedEvent
          kind: substrate/EventHandler
          filter:
            module: brmlAssets
            method: Burned
        - handler: assetsBlock
          kind: substrate/BlockHandler
        - handler: vtokenMintMintedEvent
          kind: substrate/EventHandler
          filter:
            module: vtokenMint
            method: Minted
        - handler: vtokenMintRedeemStartedEvent
          kind: substrate/EventHandler
          filter:
            module: vtokenMint
            method: RedeemStarted
        - handler: aprBlock
          kind: substrate/BlockHandler
        - handler: revenueBlock
          kind: substrate/BlockHandler
        - handler: mktPriceBlock
          kind: substrate/BlockHandler
