global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'bifrost-monitor'

rule_files:
  - "rule_node.yml"
  - "rule_para.yml"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'substrate-node'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'substrate-node:9615' ]

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'node-exporter:9100' ]

