apiVersion: 1

datasources:
        - name: postgres-12
          type: postgres
          url: postgres:5432
          database: postgres
          user: postgres
          secureJsonData:
                  password: 'postgres'
          jsonData:
                  sslmode: 'disable'
                  maxOpenConns: 0
                  maxIdleConns: 2
                  connMaxLifetime: 14400
                  postgresVersion: 12
                  timescaledb: false
