{
 "title": "assets",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Transaction Amount(Non cross chain)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"KSM\"\nFROM total_transfers\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"token\":\"KSM\"}' AND\n  method ~* 'Transfer'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"KAR\"\nFROM total_transfers\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"token\":\"KAR\"}' AND\n  method ~* 'Transfer'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"BNC\"\nFROM total_transfers\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"native\":\"BNC\"}' AND\n  section = 'balances' AND\n  method = 'Transfer'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"KUSD\"\nFROM total_transfers\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"stable\":\"KUSD\"}' AND\n  method ~* 'Transfer'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"ZLK\"\nFROM total_transfers\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"token\":\"ZLK\"}' AND\n  method ~* 'Transfer'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"vsBond\"\nFROM total_transfers\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency !~* '{\"vsBond\":'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Transaction Amount(cross out)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"KSM\"\nFROM xtokens_transferreds\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"token\":\"KSM\"}'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"KUSD\"\nFROM xtokens_transferreds\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"stable\":\"KUSD\"}'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"BNC\"\nFROM xtokens_transferreds\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"native\":\"BNC\"}'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"vsKSM\"\nFROM xtokens_transferreds\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"vsToken\":\"KSM\"}'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Transaction(Non cross chain)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  count(balance) AS \"KSM\"\nFROM total_transfers\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"token\":\"KSM\"}' AND\n  method ~* 'Transfer'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  count(balance) AS \"KAR\"\nFROM total_transfers\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"token\":\"KAR\"}' AND\n  method ~* 'Transfer'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  count(balance) AS \"BNC\"\nFROM total_transfers\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"native\":\"BNC\"}' AND\n  section = 'balances' AND\n  method = 'Transfer'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  count(balance) AS \"KUSD\"\nFROM total_transfers\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"stable\":\"KUSD\"}' AND\n  method ~* 'Transfer'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  count(balance) AS \"ZLK\"\nFROM total_transfers\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"token\":\"ZLK\"}' AND\n  method ~* 'Transfer'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  count(balance) AS \"vsBond\"\nFROM total_transfers\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency !~* '{\"vsBond\":'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Transaction(cross out)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  count(balance) AS \"KSM\"\nFROM xtokens_transferreds\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"token\":\"KSM\"}'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  count(balance) AS \"KUSD\"\nFROM xtokens_transferreds\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"stable\":\"KUSD\"}'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  count(balance) AS \"BNC\"\nFROM xtokens_transferreds\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"native\":\"BNC\"}'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  count(balance) AS \"vsKSM\"\nFROM xtokens_transferreds\nWHERE\n  $__timeFilter(block_timestamp) AND\n  currency = '{\"vsToken\":\"KSM\"}'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}