{
 "title": "salp",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Ksm Contribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"total\"\nFROM ksm_fund_contributed\nWHERE\n  $__timeFilter(block_timestamp)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"success\"\nFROM ksm_success_fund_contributed\nWHERE\n  $__timeFilter(block_timestamp)\nGROUP BY 1\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"failed\"\nFROM ksm_failed_fund_contributed\nWHERE\n  $__timeFilter(block_timestamp)\nGROUP BY 1\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"redeemed\"\nFROM ksm_success_fund_refunded\nWHERE\n  $__timeFilter(block_timestamp)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"refunded\"\nFROM ksm_failed_fund_refunded\nWHERE\n  $__timeFilter(block_timestamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Dot Contribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"total\"\nFROM dot_fund_contributed\nWHERE\n  $__timeFilter(block_timestamp)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"success\"\nFROM dot_success_fund_contributed\nWHERE\n  $__timeFilter(block_timestamp)\nGROUP BY 1\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"failed\"\nFROM dot_failed_fund_contributed\nWHERE\n  $__timeFilter(block_timestamp)\nGROUP BY 1\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"redeemed\"\nFROM ksm_success_fund_refunded\nWHERE\n  $__timeFilter(block_timestamp)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(block_timestamp,$__interval),\n  sum(balance)/1000000000000 AS \"refunded\"\nFROM ksm_failed_fund_refunded\nWHERE\n  $__timeFilter(block_timestamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "By status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time\",\n  method::text AS \"metrics\",\n  count(*) AS \"value\"\nFROM salp_contributions t\nGROUP BY t.method\nORDER BY 1 desc"
    }
   ]
  },
  {
   "title": "UnConfirmed Contributions with Alert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select block_timestamp as time,account::text,para_id::text,balance as contribution from unconfirmed_contributions\n"
    }
   ]
  },
  {
   "title": "Top contributor in fund",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", para_id::text AS metric, contributed/1000000000000 as value FROM top_contributors"
    }
   ]
  },
  {
   "title": "Large Contribution or Refund",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select block_timestamp as time,account::text,para_id::text,balance as contribution from large_fund_operation\n"
    }
   ]
  }
 ]
}